// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type AccessLinkResponse = {
    id?: string;
    token?: string | null;
    permission?: string | null;
    isActive?: boolean;
    createdAt?: string;
    maxUses?: number | null;
    useCount?: number;
};

export type ActiveUserResponse = {
    displayName?: string | null;
    role?: string | null;
};

export type AddCollaboratorRequest = {
    email: string;
    role: string;
};

export type AnonymousGrantResponse = {
    grantId?: string;
    displayName?: string | null;
    email?: string | null;
    permission?: string | null;
    lastSeenAt?: string;
    viaLinkId?: string;
};

export type AnonymousJoinResponse = {
    documentId?: string;
    title?: string | null;
    ownerDisplayName?: string | null;
    role?: string | null;
    grantId?: string;
};

export type AnonymousLinkResponse = {
    id?: string;
    token?: string | null;
    permission?: string | null;
    isActive?: boolean;
    createdAt?: string;
};

export type AuthResponse = {
    id?: string;
    email?: string | null;
    displayName?: string | null;
};

export type ChangeEmailRequest = {
    newEmail: string;
    currentPassword: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type CollaboratorListResponse = {
    collaborators?: Array<CollaboratorResponse> | null;
    anonymousUsers?: Array<AnonymousGrantResponse> | null;
};

export type CollaboratorResponse = {
    userId?: string;
    email?: string | null;
    displayName?: string | null;
    role?: string | null;
    addedAt?: string;
};

export type CreateAccessLinkRequest = {
    permission: string;
    maxUses?: number | null;
};

export type CreateAnonymousLinkRequest = {
    permission: string;
};

export type CreateDocumentRequest = {
    title?: string | null;
    templateId?: string | null;
};

export type CreateVersionRequest = {
    label?: string | null;
    message?: string | null;
};

export type DocumentListResponse = {
    id?: string;
    title?: string | null;
    ownerDisplayName?: string | null;
    updatedAt?: string;
    role?: string | null;
};

export type DocumentResponse = {
    id?: string;
    title?: string | null;
    ownerDisplayName?: string | null;
    entrypoint?: string | null;
    createdAt?: string;
    updatedAt?: string;
    role?: string | null;
    accessorDisplayName?: string | null;
};

export type FileResponse = {
    id?: string;
    filename?: string | null;
    contentType?: string | null;
    size?: number | null;
    isCollaborative?: boolean;
    category?: string | null;
    uploadedByDisplayName?: string | null;
    createdAt?: string;
};

export type FolderDeleteRequest = {
    path: string;
};

export type FolderRenameRequest = {
    from: string;
    to?: string | null;
};

export type IResult = {
    [key: string]: never;
};

export type JoinResponse = {
    documentId?: string;
    title?: string | null;
    ownerDisplayName?: string | null;
    role?: string | null;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RegisterRequest = {
    email: string;
    displayName: string;
    password: string;
};

export type RenameFileRequest = {
    newFilename: string;
};

export type SaveAsTemplateRequest = {
    title: string;
    description?: string | null;
    category: string;
    isPublic?: boolean;
    fileIds: Array<string>;
};

export type TemplateFileResponse = {
    id?: string;
    filename?: string | null;
    contentType?: string | null;
    size?: number;
};

export type TemplateListResponse = {
    id?: string;
    slug?: string | null;
    title?: string | null;
    description?: string | null;
    category?: string | null;
    isSystem?: boolean;
    isPublic?: boolean;
    ownerDisplayName?: string | null;
    createdAt?: string;
};

export type TemplateResponse = {
    id?: string;
    slug?: string | null;
    title?: string | null;
    description?: string | null;
    category?: string | null;
    isSystem?: boolean;
    isPublic?: boolean;
    ownerDisplayName?: string | null;
    createdAt?: string;
    content?: string | null;
    files?: Array<TemplateFileResponse> | null;
};

export type UpdateCollaboratorRoleRequest = {
    role: string;
};

export type UpdateDocumentRequest = {
    title?: string | null;
    entrypoint?: string | null;
};

export type UpdateMeRequest = {
    displayName: string;
};

export type UpdateTemplateRequest = {
    title?: string | null;
    description?: string | null;
    category?: string | null;
    isPublic?: boolean | null;
};

export type VersionResponse = {
    id?: string;
    label?: string | null;
    message?: string | null;
    creatorDisplayName?: string | null;
    createdAt?: string;
    sourceText?: string | null;
};

export type PostApiJoinAnonymousByTokenData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/join/anonymous/{token}';
};

export type PostApiJoinAnonymousByTokenErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiJoinAnonymousByTokenResponses = {
    /**
     * Success
     */
    200: AnonymousJoinResponse;
};

export type PostApiJoinAnonymousByTokenResponse = PostApiJoinAnonymousByTokenResponses[keyof PostApiJoinAnonymousByTokenResponses];

export type GetApiDocumentsByDocumentIdAnonymousLinksData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/anonymous-links';
};

export type GetApiDocumentsByDocumentIdAnonymousLinksErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByDocumentIdAnonymousLinksResponses = {
    /**
     * Success
     */
    200: Array<AnonymousLinkResponse>;
};

export type GetApiDocumentsByDocumentIdAnonymousLinksResponse = GetApiDocumentsByDocumentIdAnonymousLinksResponses[keyof GetApiDocumentsByDocumentIdAnonymousLinksResponses];

export type PostApiDocumentsByDocumentIdAnonymousLinksData = {
    body: CreateAnonymousLinkRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/anonymous-links';
};

export type PostApiDocumentsByDocumentIdAnonymousLinksErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiDocumentsByDocumentIdAnonymousLinksResponses = {
    /**
     * Created
     */
    201: AnonymousLinkResponse;
};

export type PostApiDocumentsByDocumentIdAnonymousLinksResponse = PostApiDocumentsByDocumentIdAnonymousLinksResponses[keyof PostApiDocumentsByDocumentIdAnonymousLinksResponses];

export type DeleteApiDocumentsByDocumentIdAnonymousLinksByLinkIdData = {
    body?: never;
    path: {
        documentId: string;
        linkId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/anonymous-links/{linkId}';
};

export type DeleteApiDocumentsByDocumentIdAnonymousLinksByLinkIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiDocumentsByDocumentIdAnonymousLinksByLinkIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Conflict
     */
    409: unknown;
};

export type PostApiAuthRegisterResponses = {
    /**
     * Success
     */
    200: AuthResponse;
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PostApiAuthLoginResponses = {
    /**
     * Success
     */
    200: AuthResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetApiAuthMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetApiAuthMeResponses = {
    /**
     * Success
     */
    200: AuthResponse;
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type PatchApiAuthMeData = {
    body: UpdateMeRequest;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type PatchApiAuthMeErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PatchApiAuthMeResponses = {
    /**
     * Success
     */
    200: AuthResponse;
};

export type PatchApiAuthMeResponse = PatchApiAuthMeResponses[keyof PatchApiAuthMeResponses];

export type PostApiAuthChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/change-password';
};

export type PostApiAuthChangePasswordErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PostApiAuthChangePasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthChangeEmailData = {
    body: ChangeEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/change-email';
};

export type PostApiAuthChangeEmailErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostApiAuthChangeEmailResponses = {
    /**
     * Success
     */
    200: AuthResponse;
};

export type PostApiAuthChangeEmailResponse = PostApiAuthChangeEmailResponses[keyof PostApiAuthChangeEmailResponses];

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDocumentsByDocumentIdCollaboratorsData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/collaborators';
};

export type GetApiDocumentsByDocumentIdCollaboratorsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByDocumentIdCollaboratorsResponses = {
    /**
     * Success
     */
    200: CollaboratorListResponse;
};

export type GetApiDocumentsByDocumentIdCollaboratorsResponse = GetApiDocumentsByDocumentIdCollaboratorsResponses[keyof GetApiDocumentsByDocumentIdCollaboratorsResponses];

export type PostApiDocumentsByDocumentIdCollaboratorsData = {
    body: AddCollaboratorRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/collaborators';
};

export type PostApiDocumentsByDocumentIdCollaboratorsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostApiDocumentsByDocumentIdCollaboratorsResponses = {
    /**
     * Created
     */
    201: CollaboratorResponse;
};

export type PostApiDocumentsByDocumentIdCollaboratorsResponse = PostApiDocumentsByDocumentIdCollaboratorsResponses[keyof PostApiDocumentsByDocumentIdCollaboratorsResponses];

export type DeleteApiDocumentsByDocumentIdCollaboratorsByUserIdData = {
    body?: never;
    path: {
        documentId: string;
        userId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/collaborators/{userId}';
};

export type DeleteApiDocumentsByDocumentIdCollaboratorsByUserIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiDocumentsByDocumentIdCollaboratorsByUserIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiDocumentsByDocumentIdCollaboratorsByUserIdData = {
    body: UpdateCollaboratorRoleRequest;
    path: {
        documentId: string;
        userId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/collaborators/{userId}';
};

export type PutApiDocumentsByDocumentIdCollaboratorsByUserIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutApiDocumentsByDocumentIdCollaboratorsByUserIdResponses = {
    /**
     * Success
     */
    200: CollaboratorResponse;
};

export type PutApiDocumentsByDocumentIdCollaboratorsByUserIdResponse = PutApiDocumentsByDocumentIdCollaboratorsByUserIdResponses[keyof PutApiDocumentsByDocumentIdCollaboratorsByUserIdResponses];

export type PostApiDocumentsByIdCompileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/compile';
};

export type PostApiDocumentsByIdCompileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    422: unknown;
};

export type PostApiDocumentsByIdCompileResponses = {
    /**
     * Success
     */
    200: IResult;
};

export type PostApiDocumentsByIdCompileResponse = PostApiDocumentsByIdCompileResponses[keyof PostApiDocumentsByIdCompileResponses];

export type GetApiDocumentsByIdStateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/state';
};

export type GetApiDocumentsByIdStateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByIdStateResponses = {
    /**
     * Success
     */
    200: IResult;
    /**
     * No Content
     */
    204: void;
};

export type GetApiDocumentsByIdStateResponse = GetApiDocumentsByIdStateResponses[keyof GetApiDocumentsByIdStateResponses];

export type PutApiDocumentsByIdStateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/state';
};

export type PutApiDocumentsByIdStateErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    413: unknown;
};

export type PutApiDocumentsByIdStateResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDocumentsByIdExportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/export';
};

export type GetApiDocumentsByIdExportErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByIdExportResponses = {
    /**
     * Success
     */
    200: IResult;
};

export type GetApiDocumentsByIdExportResponse = GetApiDocumentsByIdExportResponses[keyof GetApiDocumentsByIdExportResponses];

export type GetApiDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/documents';
};

export type GetApiDocumentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetApiDocumentsResponses = {
    /**
     * Success
     */
    200: Array<DocumentListResponse>;
};

export type GetApiDocumentsResponse = GetApiDocumentsResponses[keyof GetApiDocumentsResponses];

export type PostApiDocumentsData = {
    body: CreateDocumentRequest;
    path?: never;
    query?: never;
    url: '/api/documents';
};

export type PostApiDocumentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiDocumentsResponses = {
    /**
     * Created
     */
    201: DocumentResponse;
};

export type PostApiDocumentsResponse = PostApiDocumentsResponses[keyof PostApiDocumentsResponses];

export type DeleteApiDocumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}';
};

export type DeleteApiDocumentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiDocumentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDocumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}';
};

export type GetApiDocumentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByIdResponses = {
    /**
     * Success
     */
    200: DocumentResponse;
};

export type GetApiDocumentsByIdResponse = GetApiDocumentsByIdResponses[keyof GetApiDocumentsByIdResponses];

export type PutApiDocumentsByIdData = {
    body: UpdateDocumentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}';
};

export type PutApiDocumentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutApiDocumentsByIdResponses = {
    /**
     * Success
     */
    200: DocumentResponse;
};

export type PutApiDocumentsByIdResponse = PutApiDocumentsByIdResponses[keyof PutApiDocumentsByIdResponses];

export type GetApiDocumentsByIdActiveUsersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/active-users';
};

export type GetApiDocumentsByIdActiveUsersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByIdActiveUsersResponses = {
    /**
     * Success
     */
    200: Array<ActiveUserResponse>;
};

export type GetApiDocumentsByIdActiveUsersResponse = GetApiDocumentsByIdActiveUsersResponses[keyof GetApiDocumentsByIdActiveUsersResponses];

export type GetApiDocumentsByIdFilesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/files';
};

export type GetApiDocumentsByIdFilesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByIdFilesResponses = {
    /**
     * Success
     */
    200: Array<FileResponse>;
};

export type GetApiDocumentsByIdFilesResponse = GetApiDocumentsByIdFilesResponses[keyof GetApiDocumentsByIdFilesResponses];

export type PostApiDocumentsByIdFilesData = {
    body?: {
        file: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/files';
};

export type PostApiDocumentsByIdFilesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    413: unknown;
    /**
     * Client Error
     */
    415: unknown;
};

export type PostApiDocumentsByIdFilesResponses = {
    /**
     * Created
     */
    201: FileResponse;
};

export type PostApiDocumentsByIdFilesResponse = PostApiDocumentsByIdFilesResponses[keyof PostApiDocumentsByIdFilesResponses];

export type PostApiDocumentsByIdFilesByOldFileIdReplaceData = {
    body?: {
        file: Blob | File;
    };
    path: {
        id: string;
        oldFileId: string;
    };
    query?: never;
    url: '/api/documents/{id}/files/{oldFileId}/replace';
};

export type PostApiDocumentsByIdFilesByOldFileIdReplaceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Client Error
     */
    413: unknown;
    /**
     * Client Error
     */
    415: unknown;
};

export type PostApiDocumentsByIdFilesByOldFileIdReplaceResponses = {
    /**
     * Created
     */
    201: FileResponse;
};

export type PostApiDocumentsByIdFilesByOldFileIdReplaceResponse = PostApiDocumentsByIdFilesByOldFileIdReplaceResponses[keyof PostApiDocumentsByIdFilesByOldFileIdReplaceResponses];

export type DeleteApiDocumentsByIdFilesByFileIdData = {
    body?: never;
    path: {
        id: string;
        fileId: string;
    };
    query?: never;
    url: '/api/documents/{id}/files/{fileId}';
};

export type DeleteApiDocumentsByIdFilesByFileIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiDocumentsByIdFilesByFileIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDocumentsByIdFilesByFileIdData = {
    body?: never;
    path: {
        id: string;
        fileId: string;
    };
    query?: never;
    url: '/api/documents/{id}/files/{fileId}';
};

export type GetApiDocumentsByIdFilesByFileIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByIdFilesByFileIdResponses = {
    /**
     * Success
     */
    200: IResult;
};

export type GetApiDocumentsByIdFilesByFileIdResponse = GetApiDocumentsByIdFilesByFileIdResponses[keyof GetApiDocumentsByIdFilesByFileIdResponses];

export type PatchApiDocumentsByIdFilesByFileIdData = {
    body: RenameFileRequest;
    path: {
        id: string;
        fileId: string;
    };
    query?: never;
    url: '/api/documents/{id}/files/{fileId}';
};

export type PatchApiDocumentsByIdFilesByFileIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PatchApiDocumentsByIdFilesByFileIdResponses = {
    /**
     * Success
     */
    200: FileResponse;
};

export type PatchApiDocumentsByIdFilesByFileIdResponse = PatchApiDocumentsByIdFilesByFileIdResponses[keyof PatchApiDocumentsByIdFilesByFileIdResponses];

export type PostApiDocumentsByIdFilesByFileIdDuplicateData = {
    body?: never;
    path: {
        id: string;
        fileId: string;
    };
    query?: never;
    url: '/api/documents/{id}/files/{fileId}/duplicate';
};

export type PostApiDocumentsByIdFilesByFileIdDuplicateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiDocumentsByIdFilesByFileIdDuplicateResponses = {
    /**
     * Created
     */
    201: FileResponse;
};

export type PostApiDocumentsByIdFilesByFileIdDuplicateResponse = PostApiDocumentsByIdFilesByFileIdDuplicateResponses[keyof PostApiDocumentsByIdFilesByFileIdDuplicateResponses];

export type PostApiDocumentsByIdFoldersRenameData = {
    body: FolderRenameRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/folders/rename';
};

export type PostApiDocumentsByIdFoldersRenameErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostApiDocumentsByIdFoldersRenameResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiDocumentsByIdFoldersDeleteData = {
    body: FolderDeleteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/folders/delete';
};

export type PostApiDocumentsByIdFoldersDeleteErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostApiDocumentsByIdFoldersDeleteResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiJoinByTokenData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/join/{token}';
};

export type PostApiJoinByTokenErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    410: unknown;
};

export type PostApiJoinByTokenResponses = {
    /**
     * Success
     */
    200: JoinResponse;
};

export type PostApiJoinByTokenResponse = PostApiJoinByTokenResponses[keyof PostApiJoinByTokenResponses];

export type GetApiDocumentsByDocumentIdLinksData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/links';
};

export type GetApiDocumentsByDocumentIdLinksErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByDocumentIdLinksResponses = {
    /**
     * Success
     */
    200: Array<AccessLinkResponse>;
};

export type GetApiDocumentsByDocumentIdLinksResponse = GetApiDocumentsByDocumentIdLinksResponses[keyof GetApiDocumentsByDocumentIdLinksResponses];

export type PostApiDocumentsByDocumentIdLinksData = {
    body: CreateAccessLinkRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/links';
};

export type PostApiDocumentsByDocumentIdLinksErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiDocumentsByDocumentIdLinksResponses = {
    /**
     * Created
     */
    201: AccessLinkResponse;
};

export type PostApiDocumentsByDocumentIdLinksResponse = PostApiDocumentsByDocumentIdLinksResponses[keyof PostApiDocumentsByDocumentIdLinksResponses];

export type DeleteApiDocumentsByDocumentIdLinksByLinkIdData = {
    body?: never;
    path: {
        documentId: string;
        linkId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/links/{linkId}';
};

export type DeleteApiDocumentsByDocumentIdLinksByLinkIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiDocumentsByDocumentIdLinksByLinkIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        category?: string;
    };
    url: '/api/templates';
};

export type GetApiTemplatesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetApiTemplatesResponses = {
    /**
     * Success
     */
    200: Array<TemplateListResponse>;
};

export type GetApiTemplatesResponse = GetApiTemplatesResponses[keyof GetApiTemplatesResponses];

export type DeleteApiTemplatesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/templates/{id}';
};

export type DeleteApiTemplatesByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiTemplatesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiTemplatesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/templates/{id}';
};

export type GetApiTemplatesByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiTemplatesByIdResponses = {
    /**
     * Success
     */
    200: TemplateResponse;
};

export type GetApiTemplatesByIdResponse = GetApiTemplatesByIdResponses[keyof GetApiTemplatesByIdResponses];

export type PatchApiTemplatesByIdData = {
    body: UpdateTemplateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/templates/{id}';
};

export type PatchApiTemplatesByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PatchApiTemplatesByIdResponses = {
    /**
     * Success
     */
    200: TemplateListResponse;
};

export type PatchApiTemplatesByIdResponse = PatchApiTemplatesByIdResponses[keyof PatchApiTemplatesByIdResponses];

export type GetApiTemplatesCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/templates/categories';
};

export type GetApiTemplatesCategoriesResponses = {
    /**
     * Success
     */
    200: Array<string>;
};

export type GetApiTemplatesCategoriesResponse = GetApiTemplatesCategoriesResponses[keyof GetApiTemplatesCategoriesResponses];

export type PostApiDocumentsByIdSaveAsTemplateData = {
    body: SaveAsTemplateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/documents/{id}/save-as-template';
};

export type PostApiDocumentsByIdSaveAsTemplateErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    413: unknown;
    /**
     * Client Error
     */
    422: unknown;
};

export type PostApiDocumentsByIdSaveAsTemplateResponses = {
    /**
     * Created
     */
    201: TemplateResponse;
};

export type PostApiDocumentsByIdSaveAsTemplateResponse = PostApiDocumentsByIdSaveAsTemplateResponses[keyof PostApiDocumentsByIdSaveAsTemplateResponses];

export type GetApiDocumentsByDocumentIdVersionsData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/versions';
};

export type GetApiDocumentsByDocumentIdVersionsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiDocumentsByDocumentIdVersionsResponses = {
    /**
     * Success
     */
    200: Array<VersionResponse>;
};

export type GetApiDocumentsByDocumentIdVersionsResponse = GetApiDocumentsByDocumentIdVersionsResponses[keyof GetApiDocumentsByDocumentIdVersionsResponses];

export type PostApiDocumentsByDocumentIdVersionsData = {
    body: CreateVersionRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/versions';
};

export type PostApiDocumentsByDocumentIdVersionsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiDocumentsByDocumentIdVersionsResponses = {
    /**
     * Created
     */
    201: VersionResponse;
};

export type PostApiDocumentsByDocumentIdVersionsResponse = PostApiDocumentsByDocumentIdVersionsResponses[keyof PostApiDocumentsByDocumentIdVersionsResponses];

export type DeleteApiDocumentsByDocumentIdVersionsByVersionIdData = {
    body?: never;
    path: {
        documentId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/versions/{versionId}';
};

export type DeleteApiDocumentsByDocumentIdVersionsByVersionIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiDocumentsByDocumentIdVersionsByVersionIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDocumentsByDocumentIdVersionsByVersionIdData = {
    body?: never;
    path: {
        documentId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/versions/{versionId}';
};

export type GetApiDocumentsByDocumentIdVersionsByVersionIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    422: unknown;
};

export type GetApiDocumentsByDocumentIdVersionsByVersionIdResponses = {
    /**
     * Success
     */
    200: VersionResponse;
};

export type GetApiDocumentsByDocumentIdVersionsByVersionIdResponse = GetApiDocumentsByDocumentIdVersionsByVersionIdResponses[keyof GetApiDocumentsByDocumentIdVersionsByVersionIdResponses];

export type PostApiDocumentsByDocumentIdVersionsByVersionIdRestoreData = {
    body?: never;
    path: {
        documentId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/documents/{documentId}/versions/{versionId}/restore';
};

export type PostApiDocumentsByDocumentIdVersionsByVersionIdRestoreErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Client Error
     */
    422: unknown;
};

export type PostApiDocumentsByDocumentIdVersionsByVersionIdRestoreResponses = {
    /**
     * Success
     */
    200: unknown;
};
